### ISSUE TITLE
About Installation 

### ISSUE THREAD

**Issue by Mervespm** [ShubhzDev/Hyperledger_fabric_Bank_simple#1]
Could you explain me how to set up? It is really urgent. Your job is great

**Comment by ShubhzDev** [comment]
To generate Certifacte and Crypto Material
Run ./generate.sh this fill to create all necessary file and folder inside the artifact/channel/

To Start Network
Run ./start_network.sh file this file run your hyperledger fabric network.

To install Chaincode
Run ./installchaincode.sh 

Run ./teardown.sh file this file remove all docker container.

**Comment by Mervespm** [comment]
`Error: failed to create deliver client for orderer: orderer client failed to connect to localhost:7050: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp 127.0.0.1:7050: connect: connection refused"`

I am getting this error when i tried ti start network. I checked the logs.
How i can overcome this. Could you please help me?

<img width="1119" alt="Screenshot 2023-05-07 at 11 54 28" src="https://user-images.githubusercontent.com/88487330/236667871-0435d1a5-b232-45d1-b3b1-54cab5036aa0.png">
